application: bymaxh
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

inbound_services:
- mail

handlers:
- url: /_ah/mail/postman@.+
  script: mail.app

- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /mail/.*
  script: mail.app
  login: admin

- url: /.*
  script: web.app